---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true

  tasks:
    - name: Upgrade all packages to their latest version
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600    # 1 hour
        name: "*" 
        state: latest