---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        # update: yes
        cache_valid_time: 3600    # 1 hour

    - name: Upgrade all packages to their latest version
      ansible.builtin.apt:
        name: "*" 
        state: present
        upgrade: yes 
        autoremove: yes 
        autoclean: yes

    - name: Install Binaries
      ansible.builtin.apt:
        name: 
          - cmatrix
          - ansible
          - git
          - python3
          - python3-pip
          - net-tools
          - tftp-hpa
        state: present