---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600    # 1 hour
        # name: "*" 
        # state: latest

    - name: Install Binaries
      ansible.builtin.apt:
        name: 
          - cmatrix
          # - ansible
          - git
          # - python3
          # - python3-pip
          - net-tools
          # - tftp-hpa
        state: present

  # roles:
  #   - geerlingguy.git
    - name: Install Docker using geerlingguy.docker role
      ansible.builtin.include_role:
        name: geerlingguy.docker
      become: false

    # - name: Ensure Docker service is running
    #   ansible.builtin.service:
    #     name: docker
    #     state: started
    #     enabled: true 
