---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600    # 1 hour
        name: "*" 
        state: latest

- import_playbook: binaries.yml
- import_playbook: tree.yml

  # roles:
  #   - geerlingguy.git

    # - name: Install Docker using geerlingguy.docker role
    #   ansible.builtin.include_role:
    #     name: geerlingguy.docker
      # become: false

    # - name: Ensure Docker service is running
    #   ansible.builtin.service:
    #     name: docker
    #     state: started
    #     enabled: true 
